In [1]:
import pandas as pd
d=pd.read_csv('/content/ss.csv')
print(d)

       People  Age   Height  Weight
0       kiran    17     145      45
1        ravi    18     151      55
2        raju    19     160      60
3       varun    20     149      56
4    shaistha    18     165      48
5    reethika    19     145      70
6        bose    18     120      43
7   tejaswini    19     143      49
8       sloka    19     170      54
9    varshini    19     150      52
10     sowmya    19      56      43

In [2]:
d=pd.read_excel('/content/2203A51521.xlsx')
print(d)

      People  Age   Height  Weight
0      kiran    17     145      45
1       ravi    18     151      55
2       raju    19     160      60
3      varun    20     149      56
4   shaistha    18     165      48
5   reethika    19     145      70
6       bose    18     120      43
7  tejaswini    19     143      49
8      sloka    19     170      54
9   varshini    19     150      52

In [ ]:
d=pd.read_csv('/content/shais.tsv')
print(d)

  People\tAge \tHeight\tWeight
0           kiran\t17\t145\t45
1            ravi\t18\t151\t55
2            raju\t19\t160\t60
3           varun\t20\t149\t56
4        shaistha\t18\t165\t48
5        reethika\t19\t145\t70
6            bose\t18\t120\t43
7       tejaswini\t19\t143\t49
8           sloka\t19\t170\t54
9        varshini\t19\t150\t52